### PR TITLE
synced forked repo

### PR DESCRIPTION
**Pull request by velnias75**
Please ignore the 0.9 versions for now, as this is the version currently under development and has no tag in git

### CODE REVIEW

**Comment by velnias75** [comment]
Apropos V0.9: how can I orderly set the permissions of a directory at install?
Should this be done in the `Makefile` or do *Gentoo* fix the perms like *Debian* does? On *Debian* I can set the permissions in a `preinst` script.

**Background:** if the server is run as root, it drops its priviliges by changing to `nobody:nogroup`
In order for sqlite to work, the owner of the directory the database is located in, must be  `nobody:nogroup` as well. If the server is started as normal user, the database gets installed in `$HOME/.NetMauMau`

**Comment by hasufell** [comment]
> how can I orderly set the permissions of a directory at install?

Depends... permissions of directories that already exist (like /usr or /etc) cannot be set by the ebuild (that's a white lie, though). If you throw the database somewhere in e.g. /var/lib/games/NetMauMau during runtime then you'd do
```
keepdir /var/lib/games/NetMauMau
fowners nobody:nogroup /var/lib/games/NetMauMau
```
in src_prepare!

**Comment by velnias75** [comment]
Of course I *don't* a standard dir. Actually it gets installed in `$LOCALSTATEDIR/games/NetMauMau` (which points to `/var/games/NetMauMau` on Debian).

How can I refer to `$LOCALESTATEDIR` in the ebuild? I.e. 

	keepdir $LOCALESTATEDIR/games/NetMauMau
	fowners nobody:nogroup $LOCALESTATEDIR/games/NetMauMau

**Comment by hasufell** [comment]
> Of course I don't a standard dir. Actually it gets installed in $LOCALSTATEDIR/games/NetMauMau (which points to /var/games/NetMauMau on Debian).

That's defined via an autotools configure switch
```
# ./configure --help | grep localstatedir
  --localstatedir=DIR     modifiable single-machine data [PREFIX/var]
```
which cann be passed to ```econf``` (a gentoo wrapper around ./configure) in src_configure()

**Comment by velnias75** [comment]
So far I know it :grinning: But if `--localstatedir=DIR` is **not** given, `ebuild` seems to submit a default value, or am I wrong? Else I just use `--localstatedir=/var/lib/games/NetMauMau`.

**Comment by hasufell** [comment]
I cannot use the commit of the pull request, because all version bumps are in a single commit. They should be separate and with a clean commit message. Do:
```
git reset --mixed HEAD~1
git gui
```
Now commit all ebuilds separately (commit != push in git... it's just local). For 0.6 and 0.5 you have done fixes. Then for bump to 0.7, 0.8 and 0.9 you'd do separate commits (you should also stage only the relevant lines from the Manifest... just right click on the line like ```+DIST netmaumau-0.7-server.tar.gz [...]``` and select 'Stage Line For Commit'.)
You commit anything that is in the lower left part of the window which says 'Staged Changes (Will Commit)' if you click on the Commit button.

The message format is something like
```
[games-server/netmaumau] added missing dependencies to 0.6
```
for example. A lot of git hosted projects have very strict rules about commit message format.

**Comment by hasufell** [comment]
> Else I just use --localstatedir=/var/lib/games/NetMauMau

Yes, the last value wins in autotools configure scripts.

**Comment by velnias75** [comment]
OMG :rage:  now this discussion... Ok, I will do... :disappointed_relieved:

**Comment by velnias75** [comment]
touhami3 games-overlay-fork # git gui
	git: 'gui' ist kein Git-Kommando. Siehe 'git --help'.

	Haben Sie eines von diesen gemeint?
        	gc
        	grep
        	init
        	jump
        	pull
        	push

**Comment by velnias75** [comment]
Better I **really** cannot do it for the moment and I **HOPE** we haven't that discussions as before...

**Comment by hasufell** [comment]
> I'll rebuild git with USE=tk. Hope that will help...

Yes, there is also ```gitk```, very useful.

**Comment by hasufell** [comment]
The pull request still had the 'synced forked repo' commit... it would have been nicer if that got removed... that's what
```
git reset --mixed HEAD~1
```
was meant for, because it removes the very last commit, but keeps the changes that commit has caused.

**Comment by velnias75** [comment]
I've **used** `git reset --mixed HEAD~1` :astonished:

**Comment by hasufell** [comment]
Then there was probably another commit on top of it.

Anyway... using ```gitk``` you can see the history. It's difficult to understand what effects all that stuff has if you cannot see the history visually. I use it myself in conjunction with ```git gui``` for committing. Only more advanced stuff like (interactive) rebases or things like pulling/adding remotes I do via command line.

**Comment by velnias75** [comment]
`USE=tk` made available both: `git gui` and `gitk`. If I have time, I'll take a deeper look at it, but for now my *Gentoo-VM* is busy build PyQt :angry:

**Comment by hasufell** [comment]
I now see what happened. You did the reset correct and the commits as well, but when you tried to push you got a push-conflict and tried to resolve it by re-pulling your own upstream branch.
That's why I said you should use ```git push -f origin master``` in order to overwrite the previous history (including that old commit). Ofc you never want to rewrite the history of running live branches (every fork of it will basically break)... pull request branches/repositories are sort of an exceptions.

**Pull request merged**
