### PR TITLE
Fixfix

### PR DESCRIPTION
**Pull request by velnias75**
Of course not as I wanted. Renaming with `mv` and than `git commit -a -m"Fuck you Linus"` didn't worked.
*PLEASE* **PLEASE** delete `-r1` yourself. Thanks.

### CODE REVIEW

**Comment by velnias75** [comment]
I search the way to my bed. Hope will not have nightmares about *Git*

**Comment by hasufell** [comment]
Could you elaborate what is wrong with the current ebuilds in this repository? I cannot follow you. Are the subslots wrong?

**Comment by velnias75** [comment]
I got a conflict with wrong subslots, but if you even doubt my own quality 
checks test yourself.

This damn bullshit fucking git (sorry, but I'm at total end of patience with 
it) somehow didn't used the HEAD to create to create the pull request

**Comment by hasufell** [comment]
I just don't understand why you revbumped the ebuilds another time. ```netmaumau-0.6-r1.ebuild``` is exactly the same as ```netmaumau-0.6-r2.ebuild```. Same for ```netmaumau-0.7-r2.ebuild```.

**Comment by velnias75** [comment]
Because it seems I lost all brain while using *Git*

I tell you, if my employer will ever introduce Git, I will quit that job and will search for a lone island and start a life like Robinson Crusoe.

Yes, I compared on Github they are the same. Test are running again on my machine...

**Comment by hasufell** [comment]
Breaking things and messing up is part of the learning how git works process :D

**Comment by velnias75** [comment]
Another question: before I unmerged the server first, this time not and Gentoo downgrades it without any message. Is this correct?

**Comment by velnias75** [comment]
Breaking things by using a VCS normally is a *showstopper* but why not for *Git* :question:

**Comment by hasufell** [comment]
> Breaking things by using a VCS normally is a showstopper but why not for Git

Because you just broke your local repository. To break the remote repository you have to use a force-push which is disabled on production repositories.

**Comment by velnias75** [comment]
OMG

**Comment by velnias75** [comment]
Why didn't you waited? I'm currently at the process to test if you can reject that PR ...

**Comment by hasufell** [comment]
It's just a revbump. Worst thing that happens is that the user has to recompile which takes 2min.

**Comment by velnias75** [comment]
~2:40 in version 0.11 :grinning: For a Winf*ck build add 1 Minute more

**Comment by velnias75** [comment]
Ok, we let it now as it is and I hope the PR for 0.11 won't get such a desaster. From the ebuild side not too much surprises will come, just that I removed your patch :tongue:

**Comment by hasufell** [comment]
```
# time cave resolve -z -1 games-board/netmaumau -x
[...]
real	0m16.630s
```

**Comment by velnias75** [comment]
`cave` ??????

**Comment by hasufell** [comment]
It's a different package manager. See ```sys-apps/paludis``` and http://paludis.exherbo.org/

I don't use portage.

**Comment by velnias75** [comment]
Ok, but please remember I run Gentoo in a VM and since unfortunately the VM-Disk is on the same partition as VirtualBox itself I have a performance loss on disk-IO

**Comment by velnias75** [comment]
But even then, building for Winf*ck takes longer than for Linux, even with some features disabled in Win32

**Pull request merged**
