### PR TITLE
NetMauMau 0.9

### PR DESCRIPTION
**Pull request by velnias75**
This time with help of git gui/tk.

Let's hope it is okay.

### CODE REVIEW

**Comment by hasufell** [comment]
The first commit has an incorrect commit message. You can fix that via an interactive rebase:
```
git rebase -i HEAD~2
# change 'pick' to 'edit' for the commit with the incorrect commit message
# save and quit editor
```
* start git-gui and select "ammend commit" then fix the commit message
* go back to terminal and type
```
git rebase --continue
git push -f origin PR-NetMauMau-0.9
# again... force push should only be used for pull request branches
```

**Comment by hasufell** [comment]
For understanding... if you rebase a commit ABC in the middle via 'edit' for example then git will jump back in the history so that the commit ABC looks like the most recent one. Then you can edit it via ammending or you can even add more commits. If you tell it to continue the rebase, then it will try to add all commits that followed the ABC commit in the old history.

**Comment by velnias75** [comment]
Git will **never** get a friend of mine :angry:

**Comment by hasufell** [comment]
Hmm, now we install into /var/lib/games... we could/should probably use [gamers.eclass](https://github.com/hasufell/games-overlay/blob/master/eclass/gamers.eclass) (not games.eclass). Especially because I am worried about preserving data in /var/lib/games. The eclass has methods to ensure that these are preserved + handle permission stuff (the latter might not be needed).

**Comment by hasufell** [comment]
Well, as the eclass says... permissions will probably not need to be touched since the server is expected to handle that (or we create package specific user/group). But what about data preservation across reinstallations?

**Comment by hasufell** [comment]
nvm, we don't seem to install actual files into /var/lib/games

**Comment by hasufell** [comment]
your metadata.xml files were not DTD compliant, see 1c4ee6416fb627e5c8d5343be2e7326143d6d8a1 and 2b1d2af2e4897389e37455e6a95a249a6aad8691

you can check that via ```repoman full``` from the ebuild directory

**Pull request merged**
