### PR TITLE
[games-server/netmaumau] bumped version to V0.17.1

### PR DESCRIPTION
**Pull request by velnias75**
Feel free to offer `games/server/netmaumau` 0.17.1 to your users:

* it optimizes 2 hot spots
* it needs no patch for LTO

### CODE REVIEW

**Comment by hasufell** [comment]
how hot is it really?

**Comment by hasufell** [comment]
hot, as in: HOT

**Comment by velnias75** [comment]
*VERY* hot, explanation follows...

**Comment by velnias75** [comment]
It affects both server and client (via the client library):
Whenever a card gets transmitted over the network the SUIT of the card must get transmitted. Later it needs to get converted to the internal representation. Before the optimization it was coded as an `if/else` construct comparing to each SUIT symbol.
The nature of the game, but makes it impossible to *predict* the probality of the SUIT, so the compiler can do everything but **NEVER** a reliable branch prediction.
So the solution was to put the SUITs in a *STL* `std::map`. At the first glance this looks like an endless overhead, in German *mit Kanonen auf Spatzen schießen*, **BUT** if you know **HOW** a `std::map` is implemented (based on a RB-tree) you know that it will perform in constant time which will amort over the game, so at the end the overhead will be eaten up completely. In other words, storing the SUITs in a `std::map` will improve overall lookup work a lot.

**Comment by hasufell** [comment]
> mit Kanonen auf Spatzen schießen

you could also shoot with a Schrotflinte on a Fliege

**Comment by velnias75** [comment]
Does the beer taste well?

**Comment by velnias75** [comment]
Second hot spot was *SQLite*:
After every turn the turn counter needs to get updated (incremented). Therefore a *prepared statement` was more suitable.

**Comment by hasufell** [comment]
you should upgrade to mysql/postgresql

**Comment by velnias75** [comment]
The beer tastes indeed well! (mysql/psql)

Currenty these have been the only hot spots I found. The remaining one lies outside of the scope of NetMauMau and must be located within Lua. In fact, Lua has an enourmous overhead in calls of C code.

**Comment by hasufell** [comment]
> The remaining one lies outside of the scope of NetMauMau and must be located within Lua.

switch to Go or Swift?

**Comment by velnias75** [comment]
I've just added the **Go** USE-flag on my gcc this moring :astonished:

**Comment by velnias75** [comment]
So with *THAT* optimizations it cannot get merged???

**Comment by velnias75** [comment]
**OT:** if you need hot, wait until Monday and spend your break downtown. There it will be hot enough in any meaning :grinning:

**Comment by hasufell** [comment]
I think I pushed something, but maybe it was the pint of beer?

**Pull request merged**
