### PR TITLE
NetMauMau 0.21.(0)

### PR DESCRIPTION
**Pull request by velnias75**
[games-board/netmaumau] works with Qt5 too. Do we want to offer that via an `USE` flag?

### CODE REVIEW

**Comment by hasufell** [comment]
yes, the qt/kde herd has a qt4 and a qt5 flag, we can use both

**Comment by velnias75** [comment]
Ok, but I can't download and build a Qt5 just now. 
So please merge it and if you are able to get a Qt5, could you add the flag?

**Comment by hasufell** [comment]
I don't use qt5 either currently and avoid upgrading to it because the transition is broken and causes numerous dependency blockers.

**Comment by velnias75** [comment]
So we just merge it and wait until Qt5 works better?

**Comment by velnias75** [comment]
put it (and leave) in, because it is what normally a user would expect: to play with the updated server if he/she updates it.

Also:
1) for non-heavy players, who play NetMauMau all the time they start their PC, this message will rarely appear
2) for heavy players, who play NetMauMau all the time they start their PC (like me due to developing it), it was annoying to get `root`, stop `xinetd`, stop `nmm-server` and start `xinetd` again

And why the hell wants somebody to update NetMauMau, but **not** playing with the **new** instance?

**Comment by velnias75** [comment]
If it is **soooooo** much annoying, for the next release the elog can vanish (i dislike that idea), because the detection that the server shuts down while a game is running, has improved.

**Comment by hasufell** [comment]
> And why the hell wants somebody to update NetMauMau, but not playing with the new instance?

I see your point, but the right way would be to provide an init service file for the server (like for apache etc) and then just print an elog for the user to restart the service. Ebuilds usually _never_ restart services. That's sort of a convention to leave service and process handling to the system administrator. A reason to not restart the instance would be incompatible configuration that has yet to be updated... imagine if our apache ebuild would automagically restart the server and make it choke because of that. People will get *very* angry.

**Comment by velnias75** [comment]
So tell it to the developers of (x)inetd to provide it. Currently this is the only way and since I'm apparently the only user who uses NetMauMau I want it that way. The *hand* way is too much annoying.

**Comment by velnias75** [comment]
BTW: on Debian - since eons - on every glibc update a lot of servers (**real** servers) get restarted and **nobody** complains about that.

**Comment by hasufell** [comment]
> on Debian

Debian is the last thing that is anywhere near sensible policies or QA, but I don't have a strong opinion on the current matter, hence it is already merged

**Comment by velnias75** [comment]
Also keep in mind it is a **GAME** not HA-cluster vital service.
I can conjure even if there are some users (gamers?) out there using it 
occasionally they will either never see that message and else are happy not 
to learn Linux system administration or being forced to reboot the PC if they 
just want to use the new version.

And from professional experience, don't understimate the number of servers 
running on Debian/Ubuntu server out there. They seem to rank at the top 
position followed by RedHat/CentOS and SuSE. I guess (sadly) Gentoo ranks 
higher on private PCs.

**Comment by hasufell** [comment]
> And from professional experience, don't understimate the number of servers running on Debian/Ubuntu server out there. They seem to rank at the top position followed by RedHat/CentOS and SuSE. I guess (sadly) Gentoo ranks higher on private PCs.

Sure, but that's unrelated to the fact of sensible policies or QA. MS Windows is also widely used, even for servers. It is still utter crapshit. And gentoo definitely does suck for servers. I myself prefer to run FreeBSD instances.

**Comment by hasufell** [comment]
> Also keep in mind it is a **GAME** not HA-cluster vital service.

Well yes, but there is also the thing called "consistency". Ofc consistency doesn't always make sense, but it helps to make the system (ebuilds in particular) **predictable** for the user.

**Comment by velnias75** [comment]
And I keep consistency to the the postinst-scripts of Debian.

Sorry, but my developing system is (historically) a Ubuntu Precise VM. It is 
that much heavily patched to my demands I have no time and mood to do the 
same for Gentoo.

Again: this message (and action) will appear rather rare and the user will be 
glad not to do it by hand.

I tried to convince xinetd to at least let NetMauMau stop itself if it is 
idle, but to no avail. But apart from all problems with xinetd, the 
advantages you get (esp. for a server type like NetMauMau) are overweighing 
so it is better to keep both the Debian postinst and the ebuild as it is now.

If there are serious cries from the non-existing users of NetMauMau we can 
think about it again, ok?

**Comment by hasufell** [comment]
> If there are serious cries from the non-existing users of NetMauMau we can think about it again, ok?

You could write a function that detects whether your sister plays NetMauMau :dancers:

**Comment by velnias75** [comment]
Since she has currently only a Win laptop and I'm neither Bill Gates, nor 
Google nor Mozilla it seems she will prefer to die than installing the crap 
NetMauMau, which cannot be software at all since a person who claims stupidly 
and senselessly typing and clicking and at most installing a wallpaper 
sometimes, claims Software developing is a **REAL** job.

Software can **only** and **only** origin from either Bill Gates, or Google or 
Mozilla, but never from her brother :-(

(She insists NetMauMau needs the internet. Doesn't matter **I'm** the one who 
develops it and that I claim it needs at least a loopback interface and she 
don't want to connect a Windows laptop to the internet)

Else, I'm currently getting in total rage concerning my sis, because she lied 
to me, at least never mentioned, she now has a laptop, just to avoid to test 
the crap called NetMauMau.

**Comment by velnias75** [comment]
BTW: **she** is the reason why I developed NetMauMau and also **she** is the 
reason why I designed it that way.

We both like to play Mau Mau, sometimes we did it all the day long. But there 
is some distance between us.

So I made it network aware, easy to maintain on a Linux (xinetd), portable 
(Win32) if she is either in a INet-Café or at somebodys house who offers her 
a PC. If we both cannot play together, it should be fun to play against the 
AI.

**Comment by hasufell** [comment]
NetMauMau could probably be extended for virtual dating, so I can play mau mau with an AI and afterwards fall in love with it. :heart: 

That should definitely make this software stand out.

**Comment by velnias75** [comment]
If you like cybersex, feel free to choose up to 5 attractive AI player images and link them into `/usr/share/netmaumau/ai_imgN.png`. Take care the configured user has *read access* if you use *privilege dropping*.

Now you can either write a sophisticated new sexy client in *Haskell* (emerge `games-server/netmaumau` with `USE=doc` to get the client api docs or see here: http://rangun.de/nmm-client-api-doc/) or you use the boring and sucking *Qt* client provided in `games-board/netmaumau`

**Pull request merged**
