### PR TITLE
NetMauMau 0.17 (client) & 0.17.0 (server)

### PR DESCRIPTION
**Pull request by velnias75**
Now with Lua...

### CODE REVIEW

**Comment by hasufell** [comment]
do you have lua bundled? if yes, I'd prefer that, because the gentoo lua maintainers are not reliable in their decisions

**Comment by velnias75** [comment]
It is not bundled.

**Comment by hasufell** [comment]
I'd recommend to _optionally_ bundle it in the future. Lua is a special package.

**Comment by velnias75** [comment]
Somewhere must be a limit, either the Gentoo people find new maintainers or press them to be more reliable.
Did you watched into the Lua tarball from the developers? There is nothing more easier packed than that. Not a single bit I had to touch to get it compiled in into the Win version.

So this PR will get rejected? Must know to update the README and release infos.

**Comment by hasufell** [comment]
> So this PR will get rejected?

why would it?

**Comment by hasufell** [comment]
> Did you watched into the Lua tarball from the developers?

Not only that, I even tried to fix some things... but lua upstream is uncollaborative. They don't care to standardize their build system, but except distros to hack their own stuff... which causes cross-distro breakage e.g. due to different SONAMEs, even different library names... and also unsupported pkgconfig files. There's almost nothing easy about _packaging_ lua (packaging != building).

**Comment by velnias75** [comment]
Latin American mentality... Additionally they are full scale academics and not practical people.
To fork Lua and build a fully compatible version would be no problem. So the distro people (mostly also strange headed mentalities) should throw that into the room...

**Comment by hasufell** [comment]
Also see
https://github.com/OpenRA/OpenRA/issues/6529
https://github.com/OpenRA/OpenRA/commit/2696644fa74bbaec2c980f647b26728559b00e2c
http://lua-users.org/lists/lua-l/2014-05/msg00049.html


> So the distro people (mostly also strange headed mentalities) should throw that into the room...

They (distros) simply don't work together. That's why the upstream-downstream hierarchy is so important. If one of those is uncollaborative, then the end-user gets to pick up the pieces.

**Comment by velnias75** [comment]
I believe you. But **natural dynamics** luckily work enough that at least has grown Linux into a workable system.

About the strange mentalities I have my own theories and they bring me to understand any fraction of them. But I will spare you of my quite depressive theory.

**Comment by hasufell** [comment]
> and they bring me to understand any fraction of them

but how do you know that understanding is correct?

**Comment by velnias75** [comment]
I personally can understand them. Working on the technical side of IT and additionally in private, not to earn the living with it, you can't gain golden apples of respect and glamour in the real life. This can make people bitter. Within they very own community they feel comfortable, but just one step beside it all starts to get to be enemies of them.

**Comment by hasufell** [comment]
> Within their very own community they feel comfortable

I think that is rarely true. The biggest fights are within communities.

**Comment by velnias75** [comment]
Ok, forget that line and than my other words become even more possible

I don't belong to ANY community. I'm just a lonewolf who wants to develop and 
to dig into software technics theory

**Comment by hasufell** [comment]
I think opensource communities are proof that flat hierarchy with lots of shareholders (or in other words: developers with decision making power) doesn't work very well most of the time. Both in terms of workflow and decision making.

But every time a project is a mix of company funded/controlled hierarchy and opensource collaboration... then it seems to work pretty well.

**Pull request merged**
