### PR TITLE
Fixed subslots

### PR DESCRIPTION
**Pull request by velnias75**
This was quite the hardest pull request ever. Took many hours, but I mastered it :smile_cat: 

Summary: in **much** less time, than creating this pull request, I checked all binary and source versions and
adapted the subslots, so that to every games-board/netmaumau version (client) the latest compatible games-server/netmaumau version (server) is chosen.

All chosen dependencies have been *carefully* tested for **really** being compatible and working.

If you want to do me a favor, **please** **please** accept that PR. A second time I don't want to have that *git* torture again...

### CODE REVIEW

**Comment by hasufell** [comment]
Changing dependencies is better done via a revbump. Users who already have games-board/netmaumau installed will not get the updated dependencies, because the dependencies of _installed_ packages are FIXED in the VDB (see ```/var/db/pkg/games-board/netmaumau-0.9/RDEPEND```), unless people use the portage hack called 'dynamic dependencies' which is discouraged, optional and will be removed in the future. That means they might already have a broken dependency-set and this update will not bring them the fix unless they manually rebuild the packages. Therefor it's better to do a revbump for both changes.

You can do a revbump by just renaming the ebuilds with ```-r1``` suffix and removing the old ones, all in one additional commit... no need to fix the previous commits.

**Comment by velnias75** [comment]
I just get **crazy** with this damn f*cking git! Even if I love Linux for this crazy damn shit I could **KILL** LT!

I did an error, nothing pushed to GitHub. How can I get, without cloning new *revert* my changes, so that barnch `PR-NetMauMau-subslots` is the same like on GitHub again?

**Comment by velnias75** [comment]
I can't imagine that will work, if not I really consider to boycott git for the rest of my life even if it will mean to search a new field of work in future. I'm really just **just** ANGRY with that bullshit named *Git*

**Comment by hasufell** [comment]
Well, I can ofc do the revbump myself. I just wanted to explain the reasoning. This isn't really a git issue :)

**Comment by hasufell** [comment]
Just leave the PR as it is now.

Last resort is always: clone the repository again.

**Comment by velnias75** [comment]
I already have deleted a very angry rant, because I did an error.
But is my **LAST** commit right or not?

**Comment by hasufell** [comment]
what? :D

**Comment by velnias75** [comment]
The revbumb commit?

**Comment by velnias75** [comment]
What I did was first to rename the files with 
`mv netmaumau-0.x.ebuild netmaumau-0.x-r1.ebuild`
than
`git status`, `git add [files listed as untracked]`, `git rm [files listed as removed}`

**Comment by hasufell** [comment]
You can use straight
```
git mv netmaumau-0.x.ebuild netmaumau-0.x-r1.ebuild
# same all the other ebuilds
git commit
git push origin PR-NetMauMau-subslots
```

**Comment by velnias75** [comment]
So, is the result how you wanted it?

**Comment by hasufell** [comment]
Looks like it

**Comment by hasufell** [comment]
Git is such a joy, isn't it? :dancer: 

Well... afair Linus himself said once that people want over-complicated tools, so he made one. :D

**Comment by hasufell** [comment]
An alternative would probably be mercurial which is quite different and probably a bit more similar to SVN. But I haven't dived into it yet. It's also possible to push from mercurial repos to git repos afaik. Maybe you want to look into that.

**Comment by velnias75** [comment]
I had long time the planning to have a look into *Mercurial* but just no time found for it.

**Comment by velnias75** [comment]
On `git pull upstream master` I got two conflicts. I took the upstream version, but I need to check if or what went wrong.

So expect a fix for the fix if I merged wrong...

**Comment by velnias75** [comment]
Can you give me the address of Linux to **KILL** him? Of course upstream is **BROKEN**
Fix you will get tommorrow

**Comment by velnias75** [comment]
Why the hell do I **test** it if finally it arrives broken on upstream?

**Pull request merged**
